basics:
  email: "luka.lafayedemicheaux@psl.eu"
  location:
    city: "Paris"
    countryCode: "FR"
  name: "Luka Lafaye de Micheaux"
  phone: "+33 7 86 94 84 97"
  description: "French-Canadian-Swiss | AI hackathon prize‐winner (€10 000+) | Seeking AI CIFRE PhD / AI research role."
  profiles:
    - network: "Github"
      url: "https://github.com/lukalafaye"
      username: "lukalafaye"
    - network: "Linkedin"
      url: "https://www.linkedin.com/in/lukalafaye/"
      username: "lukalafaye"
    - network: "StackOverflow"
      url: "https://stackoverflow.com/users/9246648/luka-lafaye-de-micheaux"
      username: "luka-lafaye-de-micheaux"
    - network: "Kaggle"
      url: "https://www.kaggle.com/lukalafaye/"
      username: "lukalafaye"
    - network: "Leetcode"
      url: "https://leetcode.com/u/linus84/"
      username: "linus84"


education:
  - area: "Master of Science in Artificial Intelligence"
    institution: "Université PSL"
    location: "Paris"
    countryCode: "FR"
    startDate: "2024-09-01"
    url: "https://www.topuniversities.com/universities/universite-psl"
    courses:
      - "Foundations of Machine Learning"
      - "Optimization for Machine Learning"
      - "Reinforcement Learning"
      - "Large language models"
      - "Deep learning for image analysis"
      - "Data acquisition, extraction and storage"
      - "Data Science"

  - area: "Engineering Curriculum"
    institution: "Institut Polytechnique de Paris (Telecom SudParis)"
    location: "Paris"
    countryCode: "FR"
    startDate: "2022-08-01"
    url: "https://www.topuniversities.com/universities/institut-polytechnique-de-paris"
    courses:
      - "Machine Learning"
      - "Deep Learning"
      - "Data Science"
      - "Analysis and integration"
      - "Statistics"
      - "Optimization"
      - "Algorithmics & programming"
      - "Operating systems"
      - "Probability"
      - "Signal theory"
      - "Networks"

  - area: "AI engineering exchange"
    institution: "Ecole Polytechnique Montreal"
    location: "Montreal"
    countryCode: "CA"
    startDate: "2023-08-28"
    endDate: "2023-12-14"
    url: "https://www.polymtl.ca/"
    courses:
      - "Technology Entrepreneurship"
      - "Data Mining"
      - "Machine Learning"
      - "Natural Language Processing"

  - area: "Intensive preparation for competitive entrance exams to leading French engineering schools"
    institution: "Sainte-Geneviève"
    location: "Versailles"
    countryCode: "FR"
    startDate: "2020-09-01"
    endDate: "2022-07-01"
    url: "https://www.letudiant.fr/palmares/classement-prepa/maths-spe-mp/ecole-integree-polytechnique.html"

  - area: "Baccalauréat S (U.S. equivalent high school plus one year) - 1st ranked"
    institution: "Lycee Condorcet Sydney"
    location: "Sydney"
    countryCode: "AU"
    startDate: "2018-09-01"
    endDate: "2020-06-01"
    url: "https://www.condorcet.com.au"


meta:
  breaks_before:
    education: true

hackathons:
  - name: "Privacy Hack AI Hackathon - 1st ranked - Won € 3 000"
    date: "September 2024"
    description: "Designed Parseling, an app enabling medical clinics to leverage predictive AI on patient data without compromising privacy using fully homomorphic encryption."
    url: "https://www.linkedin.com/posts/gr%C3%A9goire-guillot_ppaihack-activity-7246513638839062528-_Wa6"
    keywords:
      - "Privacy"
      - "Healthcare AI"
  - name: "SWE-Bench Hackathon (Performance Track) - 1st ranked - Won a cool sweater :)"
    date: "August 2024"
    description: "Built a tool that automatically resolves GitHub issues and achieved the best open-source performance on SWE-bench Lite (30.26%)."
    url: "https://lu.ma/eye2ec18?tk=5IjiLv"
    keywords:
      - "Software engineering"
      - "Agentic AI"
  - name: "D4Gen AI Hackathon - 3rd ranked - Won €2 500"
    date: "March 2024"
    description: "Used AlphaFold to discover a protein able to protect RNA in cells."
    url: "https://www.linkedin.com/posts/pascalviguie_we-are-honored-to-have-been-granted-the-3rd-activity-7178504478206119936-JbEQ"
    keywords:
      - "Biology"
      - "Protein language models"
  - name: "Ecole Polytechnique Montreal INF8245E ML Kaggle Hackathon - 1st ranked"
    date: "November 2023"
    description: "Developed a CNN for modified CIFAR-100 competition: applied data augmentation, SMOTE for class imbalance, hyperparameter tuning (dropout/architecture/lr scheduling)."
    url: "https://drive.google.com/file/d/1F89_Lr3IAjpp5RVGYgo7WGNqCYq8cqM3/view"
    keywords:
      - "CNN"
      - "Deep Learning"
  - name: "Hackathon eau et numérique - 1st ranked - Won € 5 000"
    date: "April 2023"
    description: "Designed an app to track & predict hydrology indicators in France using Deep Learning."
    url: "https://www.linkedin.com/posts/franckhashas_les-r%C3%A9compenses-du-hackathon-eaux-et-num%C3%A9rique-activity-7056290571115450369-6UFk"
    keywords:
      - "Hydrology"
      - "Deep Learning"

projects:
  - name: "LinkedinAutoApply"
    description: "Developed a LinkedIn auto-apply bot with customized resume and cover letter generation tailored to each job application."
    url: "https://github.com/lukalafaye/LinkedinAutoApply"
    date: "June 2025"
    keywords: 
      - "Selenium" 
      - "Scraping"
  - name: "LlamArt"
    description: "Created an on-device RAG app with a locally run 2B LLM, and finetuned YOLOv11 on a custom museum dataset for artwork detection, enabling real-time local chatbot experiences on phone (novel integration)."
    url: "https://github.com/lukalafaye/LlamArt"
    date: "February 2025"
    keywords: 
      - "YOLOv11"
      - "RAG"
  - name: "Deep Learning Lung CT-Scan Segmentation"
    description: "Trained and fine-tuned nnUNet, SegFormer, SAM2, and Swin-UNETR on private sparse medical image segmentation dataset using multiple GPUs."
    url: "https://github.com/lukalafaye/ct-scans-segmentation"
    date: "February 2025"
    keywords: 
      - "Medical AI" 
      - "Finetuning segmentation models"
  - name: "3D Point Clouds"
    description: "Implemented and analyzed point cloud processing algorithms and 3D reconstruction techniques (ICP, CT-ICP, PCA-based descriptors, PointNet classification)"
    url: "https://github.com/lukalafaye/NPM3D-Projects"
    date: "February 2025"
    keywords: 
      - "Cloud processing" 
      - "3D reconstruction"
  - name: "Segmentation Guided Diffusion for lung scan data augmentation"
    description: "Trained segmentation-guided diffusion model for generating realistic lung scans conditioned on disease-aware anatomical masks on private medical dataset."
    url: "https://github.com/lukalafaye/LungGenerationSDM"
    date: "August 2024"
    keywords: 
      - "Medical data augmentation"
      - "Stable diffusion"
  - name: "GNN movie rating prediction"
    description: "Predicted movie ratings for 610 users using a GNN model and compared it with matrix factorization, including metadata scraping. SoTA approach."
    url: "https://github.com/lukalafaye/GNN-MovieRatingPrediction"
    date: "November 2024"
    keywords: 
      - "Graph neural network"
      - "Movie rating prediction"
  - name: "Harmoniq"
    description: "Developed a React Native based social network for musicians using v0."
    url: "https://github.com/lukalafaye/Harmoniq"
    date: "November 2024"
    keywords:
      - "React Native" 
      - "PostgreSQL"
  - name: "MiniSocs Java social network"
    description: "Coded Java-based social network simulation featuring user management, moderation, and comprehensive unit testing."
    url: "https://github.com/lukalafaye/MiniSocs"
    date: "February 2024"
    keywords: 
      - "Java"
      - "Social network"
      - "Unit testing"
  - name: "AI Resume parsing"
    description: "Fine-tuned a spaCy NER model on a custom resume dataset and deployed an MLflow × Airflow pipeline for automated training and tracking."
    url: "https://github.com/lukalafaye/Harmoniq"
    date: "April 2025"
    keywords: 
      - "spaCy NER" 
      - "MLflow"
      - "Airflow"
  - name: "BioFeed"
    description: "Set up backend infrastructure + hardware kit, and developed AI forecasting models alongside a web dashboard for real-time crop monitoring. WIP."
    url: "https://github.com/BioFeed"
    date: "July 2023"
    keywords: 
      - "Image classification"
      - "Forecasting"
      - "Backend setup"
  - name: "SafeSync"
    description: "Built automatic and incremental backup C++ software using hard links to efficiently sync client folders with Linux server."
    url: "https://github.com/lukalafaye/SafeSync"
    date: "June 2023"
    keywords: 
      - "Linux"
      - "Rsync"
      - "C++"
  - name: "CrypTools"
    description: "Merged with CrypTool in 2020. The most widespread e-learning software in the field of cryptology according to Hakin9."
    url: "https://github.com/CrypTools"
    date: "January 2020"
    keywords: 
      - "Cryptography"
      - "Python" 
      - "C"
      - "C++"
      - "Java"
  - name: "HackDown"
    description: "Pure black and white responsive markdown Jekyll based blog generator."
    url: "https://github.com/lukalafaye/HackDown"
    date: "May 2020"
    keywords: 
      - "Blog generator"
      - "Jekyll"


skills:
  - name: "Programming languages"
    keywords:
      - "Python"
      - "C"
      - "C++"
      - "Java"
      - "Bash"
      - "SQL"

  - name: "Artificial intelligence"
    keywords:
      - "Deep Learning"
      - "Machine Learning"
      - "Reinforcement Learning"
      - "Graph Neural Networks"
      - "Agentic AI"

  - name: "Frameworks & libraries"
    keywords:
      - "PyTorch"
      - "TensorFlow"
      - "Keras"
      - "Scikit-learn"
      - "LangChain"
      - "LangGraph"
      - "Pandas"
      - "NumPy"
      - "Matplotlib"
      - "Seaborn"
      - "MLflow"
      - "Airflow"

  - name: "Cloud, MLOps & DevOps"
    keywords:
      - "Docker"
      - "AWS CodeDeploy"
      - "CI/CD"
      - "S3"
      - "Git"
      - "GitHub Actions"

  - name: "Languages"
    keywords:
      - "French: Native"
      - "English: Fluent/C2"
      - "Spanish: Intermediate/B2"
      - "Mandarin: HSK2"

  - name: "Soft Skills"
    keywords:
      - "Team leadership"
      - "Workshop facilitation"
      - "Problem-solving"
      - "Communication"
      - "Adaptability"

work:
  - name: "Arteris IP"
    position: "AI research intern"
    location: "Sophia Antipolis"
    countryCode: "FR"
    startDate: "2025-05-05"
    url: "https://www.arteris.com/"
    highlights:
    - "Developing a ML-based topology synthesis flow for Network-on-Chip design, using diffusion models, GNN based GANs and RL agents."
  - name: "Horiana"
    position: "Machine learning intern"
    location: "San Francisco"
    countryCode: "US"
    startDate: "2024-06-29"
    endDate: "2024-09-14"
    url: "https://horiana.com/"
    highlights:
      - "Developed an LLM-based LangChain RAG AWS app (with CI/CD and CodeDeploy) to automate the generation of medical papers using statistical studies, saving over $120,000 annually."
  - name: "JustAI"
    position: "Machine learning intern"
    location: "Paris"
    countryCode: "FR"
    startDate: "2023-06-01"
    url: "https://www.justai.co/"
    endDate: "2023-07-01"
    highlights:
      - "Trained CNNs for plant classification and developed ESP32-based sensor kits for agricultural crop monitoring."
  - name: "KRYPTOSPHERE®"
    position: "Vice president & Head of AI Division - IMT Paris"
    location: "Paris"
    countryCode: "FR"   
    startDate: "2022-10-01"
    endDate: "2023-10-01"
    url: "https://kryptosphere.org/"
    highlights:
      - "Designed and delivered deep learning workshops on CNNs, RNNs, Transformers, Reinforcement Learning, PyTorch, and other ML topics to over 30 students."

hobbies:
  - key: "fa-running"
    description: "Running - 1st place at "
    link: "https://altichrono.fr/resultats/bikerun/"
    link_text: "Bike & Run 2022"
  - key: "fa-umbrella-beach"
    description: "Exploring cultures: Cuba, Cambodia, China, New Zealand, Spain, Belgium & The Netherlands - Lived in: Australia, Canada, France, US"
  - key: "fa-futbol"
    description: "Soccer, badminton, climbing & calisthenics (10 years)"

certificates:
  - name: "Neural Networks and Deep Learning"
    url: "https://www.coursera.org/learn/neural-networks-deep-learning#syllabus"
  - name: "Improving Deep Neural Networks, Hyperparameter Tuning, Regularization and Optimization"
    url: "https://www.coursera.org/learn/deep-neural-network#syllabus"
  - name: "Deep Neural Networks with PyTorch"
    url: "https://www.coursera.org/learn/deep-neural-networks-with-pytorch#syllabus"
  - name: "Generative AI with Large Language Models"
    url: "https://www.coursera.org/learn/generative-ai-with-llms#modules"
  - name: "Computing High Distinction at UNSW (HS1511)"
    url: "https://webcms3.cse.unsw.edu.au/COMP1511/21T1/"
  - name: "Hi! PARIS Hackathon"
    url: "https://www.SmartCertificate.com/SmartCertificate/?1%7ce1bc3371-9d5c-4ef9-a565-a62f09bf94ca%7c98e8becd-c0ef-46e1-b06d-36fe055f4663"
  - name: "AI Engineering Workshop - San Francisco"
    url: "https://www.virtualbadge.io/certificate-validator?credential=8bf87d83-5253-4e1d-9cb5-02d10924701e"
